### ISSUE TITLE
Exception while updating reader

### ISSUE THREAD

**Issue by tom5079** [tom5079/Pupil#40]
Exception caused by Non-integer name in download folder

> Fatal Exception: java.lang.NumberFormatException: For input string: "몬헌1"
       at java.lang.Integer.parseInt(Integer.java:615)
       at java.lang.Integer.parseInt(Integer.java:650)
       at xyz.quaver.pupil.util.UpdateKt.updateOldReaderGalleries(update.kt:117)
       at xyz.quaver.pupil.Pupil$onCreate$1.invokeSuspend(Pupil.kt:86)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by tom5079** [comment]
Working on hotfix-40

**Comment by tom5079** [comment]
caused by renamed gallery folder
